name: Django Tests

on:
  push:
    branches:
      - main  # Définissez la branche principale de votre dépôt ici

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'  # Spécifiez la version de Python que vous utilisez
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt contenant vos dépendances
      
      - name: Run tests
        run: python manage.py test
