# Generated by Django 5.0.4 on 2024-04-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionTacheApp.utilisateur')),
            ],
        ),
    ]
