# Generated by Django 5.0.4 on 2024-04-19 10:50

import GestionTacheApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0002_sessionutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='typeCompte',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('USER', 'Standard')], default=GestionTacheApp.models.AccountType['USER'], max_length=200),
        ),
    ]
