# Generated by Django 5.0.4 on 2024-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0003_alter_utilisateur_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
