# Generated by Django 5.0.4 on 2024-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0005_alter_utilisateur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
